version: "3.7"
services:
  user-feedback:
    build:
      context: .
    image: 813076059213.dkr.ecr.us-east-1.amazonaws.com/huli-user-feedback:$VERSION
    container_name: user-feedback
    ports:
      - "5050:5050"
    environment:
      - TARGET=$TARGET
    volumes:
      - .:/code
    restart: unless-stopped